### PR TITLE
Compress safety and mission impacts fix for #1 (+11 squashed commits)

### LINKED ISSUE #1: Split safety impact into supplier / deployer safety impacts
(This was actually from @j--- I think, I just copied & pasted the text into the issue, so be careful when dereferencing the pronoun "I" in the below)
"Safety Impact" probably needs to be split up into one for the vendor and one for the applier. I think the vendor one could be re-used by a coordinator. I'd call it "public safety impact" or some such. The Applier one would be "situated safety impact" or some such.

### PR DESCRIPTION
**Pull request by ahouseholder**
Fixes #1 

Squashed commits:
[07497bd] compress SafetyImpact into PublicSafetyImpact
[6b9c932] ignore a helper xlsx file
[576f968] reset inadvertent change
[419349d] remove index on supplier csv (+1 squashed commit)
Squashed commits:
[6486a57] add full supplier csv
[6918107] remove index on simplified csv (+1 squashed commit)
Squashed commits:
[1845f90] add simplified csv
[7d07685] add combined safety/mission impact column
[52dd62a] remove duplicates after collapsing from 5-4. Keep highest outcome
[898a082] collapse two lowest mission and safety impacts into one level each and remove duplicates
[b344dea] remove row indices (make future diffs cleaner)
[420559c] copy csv files for version 2
[d07e953] fix some straggling Applier / Developers (+2 squashed commits)
Squashed commits:
[878a91d] wip commit (+1 squashed commit)
Squashed commits:
[59637d6] fix applier/deployer sub

wip commit
[80dd092] revert unintended change

### CODE REVIEW

**Comment by ahouseholder** [comment]
Notes:

- This pull request adds new csv files to the data dir: a "simple" version of the supplier and deployer tables, and a "full" version of the same. The "full" version contains the columns that feed into the sub-tables (utility, safetymission) in addition to the condensed ones. The "full" version also retains duplicate rows where the same inputs landed in a different outcome. These will need to be deduplicated once we revisit the outcomes for the revised tables.

- I moved the "exposure" section in 040_...md up so that we could have safety and mission impacts land right next to each other without having a nonsequitur section on the way to the combined SafetyMissionImpact table.

**Review by j--- — APPROVED** [review]
This all looks good to me.

**Comment by zmanion** [comment]
So does the new csv represent new trees for v2? Do we have new trees decided for v2?

**Comment by j---** [comment]
> So does the new csv represent new trees for v2? Do we have new trees decided for v2?

They're the start of new trees for v2 that address this issue. They are not finalized, because there are other issues open that will change them further. Specifically, for sure #19 and maybe #35. Also maybe #8, but based on the discussion #8 might not get implemented.

**Pull request merged**
