### PR TITLE
Feature/pyjson

### LINKED ISSUE #319: Add Critical Software decision point
I'm suggesting we add one (or more) decision points to reflect software criticality.

While I don't currently have a specific decision in mind for this to be used in, it seems likely to arise in stakeholder processes.

I am currently aware of two such Critical Software definition efforts:

1. NIST [definition](https://www.nist.gov/itl/executive-order-improving-nations-cybersecurity/critical-software-definition)
2. OSSF [working group](https://github.com/ossf/wg-securing-critical-projects)

Two approaches I can see to do this:
1. Treat the different definitions as a data mapping problem, and create a single, one-bit `Critical Software=(yes,no)` decision point. This implies documentation guidance that explains how to map NIST, OSSF, or any other such list onto the decision point. 
2. Treat each definition as its own distinct decision point, e.g., `NIST Critical Software=(yes,no)`, `OSSF Critical Software=(yes,no)` etc.  This eliminates the need for the data mapping portion of approach 1, but it leads to having more decision points addressing a fairly narrowly defined concept.

My opinion is that approach 1 is preferable, as approach 2 might be overfitting the solution to the problem. It's certainly possible to move from approach 1 to approach 2 in the future should we have a specific need to do so. But I don't think going from approach 2 to approach 1 is as easy because our decision point definitions are likely to become entrenched in a way that the data mapping approach seems more adaptable to.

This may or may not be the same as #210 which refers to High Value Assets (HVA), but we should consider both in tandem to figure out how many decision points we actually need. The part I don't understand is how do CS and HVA designations intersect in actual operational usage.

### LINKED ISSUE #325: Create python package to facilitate json round-tripping
Blocked by
- [x] #321 

Fill in more detail as needed, but at least:

- use `dataclasses_json` + `dataclasses` for the objects
- be able to generate json examples from python code to incorporate into reference documentation
- python installer for package using `pyproject.toml` https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/
- include code documentation in the reference docs as well

### LINKED ISSUE #330: Model CVSS v1, v2, v3 vector elements as decision points
Because of their ubiquitous availability in vulnerability data sets, we should provide set of decision points specifically to represent CVSS vector elements (aka _metrics_).

This would also provide us with an opportunity to further exercise our emerging decision point versioning rules, because CVSS has had more revisions over time than SSVC has.

The bulk of the work is in modeling CVSS v3 and v4, but the marginal effort to modeling CVSS v1 and v2 as well is small enough that we should just do all of them.

Edit: In order to line this up with PR #343, this issue is just going to cover v1, v2, and v3. v4 will be covered in a separate issue.

### PR DESCRIPTION
**Pull request by ahouseholder**
Reopening to keep the PR active (#328 closed automatically when I was messing with the branch), but
(a) please don't push to this branch directly while it's in draft mode, and 
(b) there are a number of comments in the thread of #328 that should be separate issues entirely. 
This PR is about getting the python stuff in place. Content changes are out of scope for this PR.

- [x] Blocked by #321

- resolves #325 
- resolves #319 
- resolves #330

### CODE REVIEW

**Comment by sei-vsarvepalli** [comment]
The relative path is what is from the root I think so 
https://github.com/ahouseholder/SSVC/blob/31de409580775cbc65cf1e5271efea9b436d09e1/src/test/test_schema.py#L12

should be more like "data/schema/Decision_Point.schema.json" like that. Also the ID field inside the schema needs to be updated to reflect the new location.  These two lines also need to be updated. 

https://github.com/ahouseholder/SSVC/blob/31de409580775cbc65cf1e5271efea9b436d09e1/data/schema/Decision_Point.schema.json#L4 

https://github.com/ahouseholder/SSVC/blob/31de409580775cbc65cf1e5271efea9b436d09e1/data/schema/Decision_Point_Group.schema.json#L4

**Comment by ahouseholder** [comment]
I will be withdrawing this PR once I've chunked it up into a series of smaller PRs.

So far that includes:
- #346 
- #343 
- #342 

There will be a few more. I'll try to remember to mention this PR when I submit them.

**Comment by ahouseholder** [comment]
Running tally: the following PRs, once merged, represent the entirety of what was originally in this PR.

- #346 
- #343 
- #342 
- #370

**Comment by ahouseholder** [comment]
All of the subsequent fragments of this PR have been merged, so this one is no longer needed as a placeholder.

**Pull request closed without merging**
