### PR TITLE
Convert docs to mkdocs, material, mermaid

### LINKED ISSUE #294: Use Diátaxis Framework to restructure SSVC documentation
The SSVC documentation has grown, and it's becoming unwieldy to try to fit everything into a single document that suits everyone's needs. Also, our experience with the CVD Guide and other such guidance shows that large PDFs tend to limit the audience to only the most dedicated readers.

_This_ issue is to open the conversation about adopting the [Diátaxis Framework](https://diataxis.fr/) to guide further development of the SSVC documentation. I intend to open a separate issue (edit: #295) to also propose making a website based on these principles as the primary SSVC documentation vehicle going forward. 

We are currently using the Diátaxis Framework to build documentation for the Vultron CVD Protocol, and it has been quite helpful in providing a clear top-level information architecture for documentation aimed at different audiences.

In a nutshell, the idea is that there are four kinds of documentation organized in two dimensions. Excerpting from [the compass](https://diataxis.fr/compass/):

| If the content describes… | …and serves the user’s… | …then it must belong to… |
| -- | -- | -- |
| practical steps | study | a tutorial |
| practical steps | work | a how-to guide |
| theoretical knowledge | work | reference |
| theoretical knowledge | study | explanation |

At this point, we'd be interested in any comments on adopting this approach.

### LINKED ISSUE #295: Move away from PDF as the main SSVC documentation vehicle
The SSVC documentation has grown, and it's becoming unwieldy to try to fit everything into a single document that suits everyone's needs. Also, our experience with the CVD Guide and other such guidance shows that large PDFs tend to limit the audience to only the most dedicated readers.

This issue is to propose making a website based as the primary SSVC documentation vehicle going forward.
Note that Issue #294 is closely related and addresses the information architecture of such a site.

In terms of specific implementation suggestions:

1.  We can maintain a static site in this repository and set it up to auto-publish to certcc.github.io/SSVC
2. I have been exploring the following tech stack in my work on [Vultron](https://github.com/CERTCC/Vultron):
    - [mkdocs](https://www.mkdocs.org/) provides markdown-to-static-site capability
    - [material for mkdocs](https://squidfunk.github.io/mkdocs-material/) provides navigation, customization, look and feel, etc. to mkdocs sites
    - [mermaid](https://mermaid.js.org/) for diagrams
    - [pandoc](https://pandoc.org/) for LaTeX-to-markdown conversion (I don't think this applies to SSVC because the only raw `.tex` we have is for the tree diagrams, which pandoc is unlikely to be able to convert anyway

Plugins are available for file inclusion and other features that allow for a lot of customization.

Note that implementing this suggestion will likely break (at least initially) the `.md`-to-`.pdf` pipeline we currently have. We should consider whether being able to construct a single PDF remains a requirement if we have a documentation website. But one alternative could be "one big markdown file that includes all the others", which would effectively require us to maintain it like a manifest, but there could be automation potential there too. My suggestion would be that we do the web site version first, then figure out whether the single PDF doc is necessary afterwards.

### PR DESCRIPTION
**Pull request by ahouseholder**
Creating this as a draft PR to start to address the following:

- fixes #295 
- fixes #294 

Periodically copying this branch to https://certcc.github.io/SSVC-staging for review

### CODE REVIEW

**Comment by ahouseholder** [comment]
I'm toggling this PR out of draft mode. Not because it contains a finished implementation of webified SSVC documentation, but because it contains a sufficient implementation that we can clean up as we go.

The difficulty in making such a large change (from a set of `.md` files that were intended to compile into a monolithic `.pdf` to a set of `.md` files intended to be a web site) is that it's highly disruptive to other tasks either in flight or enqueued, so the longer-lived this branch is, the more it inhibits forward progress.

However, that also means that we need to commit to this way forward, because merging this PR will represent a discontinuity with the past. Notably, as it stands, this branch breaks the ability to build a PDF from the assembled documentation. 

That is not to say that we couldn't reconstitute such a thing in the future. For example, a giant markdown file with 

```
{% include-markdown "file1.md" %}
{% include-markdown "file2.md" %}
...
{% include-markdown "fileN.md" %}
```

could be rendered into a PDF (hint: https://pypi.org/project/mkdocs-pandoc-plugin/ is a candidate).

As I see it, there are two major options to be had at the moment:

## Merge now, fix later

Commit to this approach, break some things now and clean them up as we go

1. merge this branch sooner than later
2. continue with content development tasks, cleaning up broken links etc. as we go
3. fix things like PDF generation afterwards

## Fix now, merge later

Fix all the anticipated breaks first, then commit to this approach

1. figure out things like PDF generation first
2. fix broken links and get the content 100% into web-ready form
3. only merge this branch once those things are done
4. continue with content development tasks

---

My strong preference is toward _merge now, fix later_, because it allows the most things to move forward in parallel. 

On the other hand, the _fix now, merge later_ approach puts us in a position of "we shouldn't do X yet because Y will mess that up, so we should wait until after Y is done to do X". And doing that could delay further content development indefinitely until we get through this bottleneck.

I'm adding more than the usual number of reviewers to this because I'd like us to have a reasonable consensus to this before we finalize the decision though.

**Comment by ahouseholder** [comment]
I should note that if there is concern about breaking https://certcc.github.io/SSVC as it currently exists (with just the ssvc-calc code), I totally get that.

One option could be that we could:
- clone the `main` branch into a `develop` branch
- retarget this PR against the `develop` branch

And we could agree by consensus to continue work against `develop` until we think we're ready to replace `main` with it.  This would be a change to how we've done it in the past by doing PRs against `main`, but it doesn't seem like an insurmountable challenge.

**Comment by ahouseholder** [comment]
Alternatively, we could

- clone `main` to a `production` branch, and reset the Github Pages publishing process to watch `production`
- merge this PR into `main` and continue on our merry way

Both the `main` / `develop` and `production` / `main` options are functionally identical, just that PRs against `main` will be a bit easier to deal with in the second than in the first.

In either case, we still need to occasionally copy either the `develop` or the `main` branch (as appropriate to the chosen option) over to the `staging` branch of the CERTCC/SSVC-staging repository to update the preview.

**Review by cgyarbrough — APPROVED** [review]
I believe we discussed this in the meeting on 9/5/23 and I agree with Allen that we should proceed with the conversion to dynamic content first. While it may be useful to have a pdf version of some sort (probably for executive review), I think that we should move to the web-based documentation and do fixes and cleanup as we go. Of course if this would go against any SEI/CMU publication standards or requirements then we should discuss that prior to heading down the online doc path.

**Comment by ahouseholder** [comment]
#304 implements _Option 2_ from [this comment](https://github.com/CERTCC/SSVC/pull/301#issuecomment-1708937803), so we can now merge this PR into `main` without affecting the published calculator (because it's now drawing from the `publish` branch instead of `main`.)

**Comment by ahouseholder** [comment]
@j--- any concerns about merging this into `main`?

**Comment by j---** [comment]
No concerns.
Sorry for the delay.

--
best,
Jono

From my mobile, please excuse brevity

**Comment by ahouseholder** [comment]
Ok, changes merged into `main`. Also synced this over to CERTCC/SSVC-staging which means it's published at https://certcc.github.io/SSVC-staging too.

**Pull request merged**
